# Generated by Django 3.1.3 on 2021-01-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout_tracker', '0003_auto_20210103_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='mistake',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'Progress'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-date_added']},
        ),
    ]
